Add Electron cross-compilation support

diff --git a/bin/build-electron b/bin/build-electron
--- a/bin/build-electron
+++ b/bin/build-electron
@@ -10,6 +10,9 @@ set -e
 BIN_DIR="$(realpath -e $(dirname $0))"
 . "${BIN_DIR}/env.sh"
 
+# Note: make sure to only use NodeJS architectures here, like x64, ia32, arm64, etc.
+TARGET_ARCH=${TARGET_ARCH:-x64}
+
 usage()
 {
     echo 'usage: build-electron [-d|-r|-c]
@@ -56,31 +59,50 @@ while [ "$1" != "" ]; do
     shift
 done
 
-get_default_platform()
-{
-    hash rustup 2>/dev/null || { echo >&2 "Make sure you have rustup installed and properly configured! Aborting."; exit 1; }
+case "$TARGET_ARCH" in
+    "x64")
+        GN_ARCH=x64
+        CARGO_ARCH=x86_64
+        ;;
+    "ia32")
+        GN_ARCH=x86
+        CARGO_ARCH=i686
+        ;;
+    "arm64")
+        GN_ARCH=arm64
+        CARGO_ARCH=aarch64
+        ;;
+    *)
+        echo "Unsupported architecture"
+        exit 1
+        ;;
+esac
 
-    case "$(rustup show active-toolchain)" in 
-        *"x86_64-apple-darwin"* )
-            echo "darwin"
-            ;;
-        *"x86_64-pc-windows"* )
-            echo "win32"
-            ;;
-        *"x86_64-unknown-linux"* )
-            echo "linux"
-            ;;
-        * )
-            echo "unknown"
-    esac
-}
+hash rustup 2>/dev/null || { echo >&2 "Make sure you have rustup installed and properly configured! Aborting."; exit 1; }
 
-DEFAULT_PLATFORM=$(get_default_platform)
-if [ "${DEFAULT_PLATFORM}" = "unknown" ]
-then
-    echo "Unknown platform detected!\nPlease make sure you have installed a valid Rust toolchain via rustup! Aborting."
-    exit 1
-fi
+RUSTFLAGS_WIN=
+
+case "$(rustup show active-toolchain)" in 
+    *"x86_64-apple-darwin"* )
+        DEFAULT_PLATFORM="darwin"
+        CARGO_TARGET="${CARGO_ARCH}-apple-darwin"
+        ;;
+    *"x86_64-pc-windows"* )
+        DEFAULT_PLATFORM="win32"
+        CARGO_TARGET="${CARGO_ARCH}-pc-windows-msvc"
+        # Static linking to prevent build errors on Windows ia32
+        RUSTFLAGS_WIN="-C target-feature=+crt-static"
+        ;;
+    *"x86_64-unknown-linux"* )
+        DEFAULT_PLATFORM="linux"
+        CARGO_TARGET="${CARGO_ARCH}-unknown-linux-gnu"
+        ;;
+    * )
+        echo "Unknown platform detected!\nPlease make sure you have installed a valid Rust toolchain via rustup! Aborting."
+        exit 1
+esac
+
+echo "Building for platform ${DEFAULT_PLATFORM}, TARGET_ARCH=${TARGET_ARCH}, GN_ARCH=${GN_ARCH}, CARGO_TARGET=${CARGO_TARGET}"
 
 export MACOSX_DEPLOYMENT_TARGET="10.10"
 
@@ -90,10 +112,10 @@ export MACOSX_DEPLOYMENT_TARGET="10.10"
 
     if [ "${BUILD_TYPE}" = "debug" ]
     then
-        gn gen -C "${OUTPUT_DIR}"/debug "--args=use_custom_libcxx=false rtc_build_examples=false rtc_build_tools=false rtc_include_tests=false rtc_enable_protobuf=false rtc_use_x11=false rtc_enable_sctp=false"
+        gn gen -C "${OUTPUT_DIR}"/debug "--args=use_custom_libcxx=false target_cpu=\"${GN_ARCH}\" rtc_build_examples=false rtc_build_tools=false rtc_include_tests=false rtc_enable_protobuf=false rtc_use_x11=false rtc_enable_sctp=false"
         ninja -C "${OUTPUT_DIR}"/debug
     else
-        gn gen -C "${OUTPUT_DIR}"/release "--args=use_custom_libcxx=false rtc_build_examples=false rtc_build_tools=false rtc_include_tests=false rtc_enable_protobuf=false rtc_use_x11=false rtc_enable_sctp=false is_debug=false"
+        gn gen -C "${OUTPUT_DIR}"/release "--args=use_custom_libcxx=false target_cpu=\"${GN_ARCH}\" rtc_build_examples=false rtc_build_tools=false rtc_include_tests=false rtc_enable_protobuf=false rtc_use_x11=false rtc_enable_sctp=false is_debug=false"
         ninja -C "${OUTPUT_DIR}"/release
     fi
 )
@@ -104,22 +126,22 @@ export MACOSX_DEPLOYMENT_TARGET="10.10"
 
     if [ "${BUILD_TYPE}" = "debug" ]
     then
-        npm_config_arch=x64 npm_config_target_arch=x64 npm_config_disturl=https://atom.io/download/electron npm_config_runtime=electron npm_config_target=11.2.0 npm_config_build_from_source=true npm_config_devdir=~/.electron-gyp OUTPUT_DIR="${OUTPUT_DIR}" cargo build --features electron
+        npm_config_arch=${TARGET_ARCH} npm_config_target_arch=${TARGET_ARCH} npm_config_disturl=https://atom.io/download/electron npm_config_runtime=electron npm_config_target=11.2.0 npm_config_build_from_source=true npm_config_devdir=~/.electron-gyp RUSTFLAGS="${RUSTFLAGS_WIN}" OUTPUT_DIR="${OUTPUT_DIR}" cargo build --target ${CARGO_TARGET} --features electron
     else
-        npm_config_arch=x64 npm_config_target_arch=x64 npm_config_disturl=https://atom.io/download/electron npm_config_runtime=electron npm_config_target=11.2.0 npm_config_build_from_source=true npm_config_devdir=~/.electron-gyp RUSTFLAGS="-C link-arg=-s" OUTPUT_DIR="${OUTPUT_DIR}" cargo build --features electron --release
+        npm_config_arch=${TARGET_ARCH} npm_config_target_arch=${TARGET_ARCH} npm_config_disturl=https://atom.io/download/electron npm_config_runtime=electron npm_config_target=11.2.0 npm_config_build_from_source=true npm_config_devdir=~/.electron-gyp RUSTFLAGS="-C link-arg=-s ${RUSTFLAGS_WIN}" OUTPUT_DIR="${OUTPUT_DIR}" cargo build --target ${CARGO_TARGET} --features electron --release
     fi
 
     if [ $DEFAULT_PLATFORM = "darwin" ]
     then
         mkdir -p ../node/build/darwin
-        cp -f target/${BUILD_TYPE}/libringrtc.dylib ../node/build/darwin/libringrtc.node
+        cp -f target/${CARGO_TARGET}/${BUILD_TYPE}/libringrtc.dylib ../node/build/darwin/libringrtc-${TARGET_ARCH}.node
     elif [ $DEFAULT_PLATFORM = "win32" ]
     then
         mkdir -p ../node/build/win32
-        cp -f target/${BUILD_TYPE}/ringrtc.dll ../node/build/win32/libringrtc.node
+        cp -f target/${CARGO_TARGET}/${BUILD_TYPE}/ringrtc.dll ../node/build/win32/libringrtc-${TARGET_ARCH}.node
     elif [ $DEFAULT_PLATFORM = "linux" ]
     then
         mkdir -p ../node/build/linux
-        cp -f target/${BUILD_TYPE}/libringrtc.so ../node/build/linux/libringrtc.node
+        cp -f target/${CARGO_TARGET}/${BUILD_TYPE}/libringrtc.so ../node/build/linux/libringrtc-${TARGET_ARCH}.node
     fi
 )
